//
//  WatchlistScenePresenter.swift
//  Tram
//
//  Created by Roman Abuzyarov on 22.03.2018.
//  Copyright (c) 2018 Tram, inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WatchlistScenePresentationLogic
{
    func presentUser(response: WatchlistScene.GetUser.Response)
}

class WatchlistScenePresenter: WatchlistScenePresentationLogic
{
    weak var viewController: WatchlistSceneDisplayLogic?
    
    // MARK: Do something
    
    func presentUser(response: WatchlistScene.GetUser.Response)
    {
        let viewModel = WatchlistScene.GetUser.ViewModel(user: response.user)
        DispatchQueue.main.async {
            self.viewController?.displayUser(viewModel: viewModel)
        }
    }
}
