//
//  SearchWorker.swift
//  tram-clean
//
//  Created by Roman Abuzyarov on 06.01.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Parse

class SearchWorker
{
    func searchMovies(query: String, onSuccess: @escaping ([Movie])->Void)
    {
        var movies = [Movie]()
        
        let query = PFQuery(className: "Movie").whereKey("title",
                                                         matchesRegex: "( \(query).*)|(\(query).*)")
        query.cachePolicy = .networkElseCache
        query.findObjectsInBackground { (objects, error) -> Void in
            if let error = error{
                print("\(error) \(error.localizedDescription)")
                return
            }
            
            if let objects = objects{
                for (_, object) in objects.enumerated(){
                    movies.append(Movie(pfo: object))
                }
                
                onSuccess(movies)
            }
        }
    }
}
