//
//  SearchInteractor.swift
//  Tram
//
//  Created by Roman Abuzyarov on 06.01.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic
{
    func searchMovies(request: Search.SearchMovies.Request)
}

protocol SearchDataStore
{
    var movie: Movie? { get set }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore
{
    var movie: Movie?
    
    var presenter: SearchPresentationLogic?
    var worker: SearchWorker?
    
    // MARK: Do something
    
    func searchMovies(request: Search.SearchMovies.Request)
    {
        worker = SearchWorker()
        worker?.searchMovies(query: request.query, onSuccess: { (movies) in
            let response = Search.SearchMovies.Response(movies: movies)
            self.presenter?.presentMovies(response: response)
        })
    }
}
