//
//  SearchRouter.swift
//  Tram
//
//  Created by Roman Abuzyarov on 06.01.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic
{
    func routeToMovieDetails(segue: UIStoryboardSegue?)
}

protocol SearchDataPassing
{
    var dataStore: SearchDataStore? { get set }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing
{
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?
    
    // MARK: Routing
    
    func routeToMovieDetails(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! MovieDetailsViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToMovieDetails(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "MovieDetailsViewController") as! MovieDetailsViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToMovieDetails(source: dataStore!, destination: &destinationDS)
            navigateToMovieDetails(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToMovieDetails(source: SearchViewController, destination: MovieDetailsViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToMovieDetails(source: SearchDataStore, destination: inout MovieDetailsDataStore)
    {
        destination.movie = source.movie
    }
}
