//
//  SearchPresenter.swift
//  Tram
//
//  Created by Roman Abuzyarov on 06.01.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic
{
    func presentMovies(response: Search.SearchMovies.Response)
    func presentTVShows(response: Search.SearchTVShows.Response)
}

class SearchPresenter: SearchPresentationLogic
{
    weak var viewController: SearchDisplayLogic?
    
    func presentMovies(response: Search.SearchMovies.Response)
    {
        let viewModel = Search.SearchMovies.ViewModel(movies: response.movies)
        DispatchQueue.main.async {
            self.viewController?.displayMovies(viewModel: viewModel)
        }
    }
    
    func presentTVShows(response: Search.SearchTVShows.Response)
    {
        let viewModel = Search.SearchTVShows.ViewModel(shows: response.shows)
        DispatchQueue.main.async {
            self.viewController?.displayTVShows(viewModel: viewModel)
        }
    }
}
