//
//  SearchWorker.swift
//  Tram
//
//  Created by Roman Abuzyarov on 06.01.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchWorker
{
    func searchMovies(query: String, onSuccess: @escaping ([Movie])->Void) {
        TmdbWorker().searchMovies(query: query, page: 1, completion: onSuccess)
    }
    
    func searchTVShows(query: String, onSuccess: @escaping ([TVShow])->Void){
        TmdbWorker().searchTVShows(query: query, page: 1, completion: onSuccess)
    }
}
