//
//  SearchModels.swift
//  Tram
//
//  Created by Roman Abuzyarov on 06.01.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
  // MARK: Use cases
  
  enum SearchMovies
  {
    struct Request
    {
        var query : String
    }
    struct Response
    {
        var movies : [Movie]
    }
    struct ViewModel
    {
        struct ShortMovie{
            var title : String
            var year : String
            var rating : String
            var stars : [String]
            var imageUrl : String
            var movie : Movie?
        }
        
        var movies : [ShortMovie]
    }
  }
}
