//
//  TVShowDetailsWorker.swift
//  Tram
//
//  Created by Roman Abuzyarov on 19.03.2018.
//  Copyright (c) 2018 Tram, inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TVShowDetailsWorker
{
    func showLists(action: Action, show: TVShow, listName: ListName, onSuccess: (ListName, Status, Action)->Void){
        LocalWorker().list(do: action, show: show, in: listName, onSuccess: onSuccess)
    }
    func episodeLists(action: Action, episode: Episode, listName: ListName, onSuccess: (ListName, Status, Action)->Void){
        LocalWorker().list(do: action, episode: episode, in: listName, onSuccess: onSuccess)
    }
    
}
