//
//  TVShowDetailsModels.swift
//  Tram
//
//  Created by Roman Abuzyarov on 19.03.2018.
//  Copyright (c) 2018 Tram, inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TVShowDetails
{
  // MARK: Use cases
  
  enum DataFilling
  {
    struct Request
    {
    }
    struct Response
    {
        var show : TVShow?
    }
    struct ViewModel
    {
        var show : TVShow?
    }
  }
}
