//
//  TVShowDetailsPresenter.swift
//  Tram
//
//  Created by Roman Abuzyarov on 19.03.2018.
//  Copyright (c) 2018 Tram, inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TVShowDetailsPresentationLogic
{
    func presentData(response: TVShowDetails.DataFilling.Response)
    func presentShowLists(response: TVShowDetails.ShowLists.Response)
    func presentEpisodeLists(response: TVShowDetails.EpisodeLists.Response)
}

class TVShowDetailsPresenter: TVShowDetailsPresentationLogic
{
    func presentShowLists(response: TVShowDetails.ShowLists.Response) {
        viewController?.displayShowLists(viewModel: TVShowDetails.ShowLists.ViewModel(list: response.list, status: response.status, action: response.action))
    }
    
    func presentEpisodeLists(response: TVShowDetails.EpisodeLists.Response) {
        viewController?.displayEpisodeLists(viewModel: TVShowDetails.EpisodeLists.ViewModel(list: response.list, status: response.status, action: response.action, episode: response.episode))
    }
    
    weak var viewController: TVShowDetailsDisplayLogic?
    
    // MARK: Do something
    
    func presentData(response: TVShowDetails.DataFilling.Response)
    {
        let viewModel = TVShowDetails.DataFilling.ViewModel(show: response.show)
        viewController?.displayData(viewModel: viewModel)
    }
}
