//
//  TVShowDetailsModels.swift
//  Tram
//
//  Created by Roman Abuzyarov on 19.03.2018.
//  Copyright (c) 2018 Tram, inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TVShowDetails
{
    // MARK: Use cases
    
    enum DataFilling
    {
        struct Request
        {
        }
        struct Response
        {
            var show : TVShow?
        }
        struct ViewModel
        {
            var show : TVShow?
        }
    }
    
    enum ShowLists{
        struct Request {
            var list: ListName
            var action : Action
        }
        struct Response {
            var list: ListName
            var status : Status
            var action : Action
        }
        struct ViewModel{
            var list: ListName
            var status : Status
            var action : Action
        }
    }
    
    enum EpisodeLists{
        struct Request {
            var list: ListName
            var action : Action
            var episode: Episode
        }
        struct Response {
            var list: ListName
            var status : Status
            var action : Action
            var episode: Episode
        }
        struct ViewModel{
            var list: ListName
            var status : Status
            var action : Action
            var episode: Episode
        }
    }
}
