//
//  TVShowDetailsPresenter.swift
//  Tram
//
//  Created by Roman Abuzyarov on 19.03.2018.
//  Copyright (c) 2018 Tram, inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TVShowDetailsPresentationLogic
{
    func presentData(response: TVShowDetails.DataFilling.Response)
}

class TVShowDetailsPresenter: TVShowDetailsPresentationLogic
{
    weak var viewController: TVShowDetailsDisplayLogic?
    
    // MARK: Do something
    
    func presentData(response: TVShowDetails.DataFilling.Response)
    {
        let viewModel = TVShowDetails.DataFilling.ViewModel(show: response.show)
        viewController?.displayData(viewModel: viewModel)
    }
}
