//
//  TVShowDetailsInteractor.swift
//  Tram
//
//  Created by Roman Abuzyarov on 19.03.2018.
//  Copyright (c) 2018 Tram, inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TVShowDetailsBusinessLogic
{
    func requestData(request: TVShowDetails.DataFilling.Request)
}

protocol TVShowDetailsDataStore
{
    var show : TVShow? {get set}
}

class TVShowDetailsInteractor: TVShowDetailsBusinessLogic, TVShowDetailsDataStore
{
    init(){
        worker = TVShowDetailsWorker()
    }
    
    var show: TVShow?
    
    var presenter: TVShowDetailsPresentationLogic?
    var worker: TVShowDetailsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func requestData(request: TVShowDetails.DataFilling.Request)
    {
        let target = show?.seasons.count ?? 0
        var count = 0
        for season in show?.seasons ?? []{
            season.loadEpisodes(onSuccess: { (s) in
                count += 1
                if count == target{
                    DispatchQueue.main.async {
                        let response = TVShowDetails.DataFilling.Response(show: self.show)
                        self.presenter?.presentData(response: response)
                    }
                }
            })
        }
    }
}
