//
//  ProfileScenePresenter.swift
//  Tram
//
//  Created by Roman Abuzyarov on 21.03.2018.
//  Copyright (c) 2018 Tram, inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileScenePresentationLogic
{
    func presentUser(response: ProfileScene.GetUser.Response)
}

class ProfileScenePresenter: ProfileScenePresentationLogic
{
    weak var viewController: ProfileSceneDisplayLogic?
    
    // MARK: Do something
    
    func presentUser(response: ProfileScene.GetUser.Response)
    {
        let viewModel = ProfileScene.GetUser.ViewModel(user: response.user)
        viewController?.displayUser(viewModel: viewModel)
    }
}
