//
//  ProfileSceneInteractor.swift
//  Tram
//
//  Created by Roman Abuzyarov on 21.03.2018.
//  Copyright (c) 2018 Tram, inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileSceneBusinessLogic
{
    func getUser(request: ProfileScene.GetUser.Request)
}

protocol ProfileSceneDataStore
{
    var id : Int? {get set}
}

class ProfileSceneInteractor: ProfileSceneBusinessLogic, ProfileSceneDataStore
{
    var id: Int?
    
    init(){
        worker = ProfileSceneWorker()
    }
    var presenter: ProfileScenePresentationLogic?
    var worker: ProfileSceneWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func getUser(request: ProfileScene.GetUser.Request)
    {
        worker?.getUser(id: id ?? -1, onSuccess: { (u) in
            let response = ProfileScene.GetUser.Response(user: u)
            self.presenter?.presentUser(response: response)
        })
        
    }
}
