//
//  JSONMovie.swift
//  Tram
//
//  Created by Roman Abuzyarov on 22.02.2018.
//  Copyright © 2018 Tram, inc. All rights reserved.
//

import Foundation

struct JSONKeys {
    static let adult = "adult"
    static let backdropPath = "backdrop_path"
    static let belongsToCollection = "belongs_to_collection"
    static let budget = "budget"
    static let genres = "genres"
    static let homepage = "homepage"
    static let id = "id"
    static let imdbId = "imdb_id"
    static let originalLanguage = "original_language"
    static let originalTitle = "original_title"
    static let overview = "overview"
    static let popularity = "popularity"
    static let posterPath = "poster_path"
    static let productionCompanies = "production_companies"
    static let productionCountries = "production_countries"
    static let releaseDate = "release_date"
    static let revenue = "revenue"
    static let runtime = "runtime"
    static let spokenLanguages = "spoken_languages"
    static let status = "status"
    static let tagline = "tagline"
    static let title = "title"
    static let video = "video"
    static let voteAverage = "vote_average"
    static let voteCount = "vote_count"
    static let credits = "credits"
    static let genreIds = "genre_ids"
    static let cast = "cast"
    static let crew = "crew"
    static let name = "name"
    static let logoPath = "logo_path"
    static let originCountry = "origin_country"
    static let iso_639_1 = "iso_639_1"
    static let iso_3166_1 = "iso_3166_1"
    static let createdBy = "created_by"
    static let episodeRunTime = "episode_run_time"
    static let firstAirDate = "first_air_date"
    static let inProduction = "in_production"
    static let languages = "languages"
    static let lastAirDate = "last_air_date"
    static let networks = "networks"
    static let numberOfEpisodes = "number_of_episodes"
    static let numberOfSeasons = "number_of_seasons"
    static let originalName = "original_name"
    static let seasons = "seasons"
    static let type = "type"
    static let _id = "_id"
    static let airDate = "air_date"
    static let episodes = "episodes"
    static let seasonNumber = "season_number"
    static let episodeNumber = "episode_number"
    static let guestStars = "guest_stars"
    static let productionCode = "production_code"
    static let stillPath = "still_path"
    static let episodeCount = "episode_count"
    static let gender = "gender"
    static let profilePath = "profile_path"
    static let castId = "cast_id"
    static let character = "character"
    static let creditId = "credit_id"
    static let order = "order"
    static let department = "department"
    static let job = "job"
    static let alsoKnownAs = "also_known_as"
    static let biography = "biography"
    static let birthday = "birthday"
    static let deathday = "deathday"
    static let placeOfBirth = "place_of_birth"
    static let headquarters = "headquarters"
    static let page = "page"
    static let totalResults = "total_results"
    static let totalPages = "total_pages"
    static let results = "results"
}
