//
//  ListsModels.swift
//  Tram
//
//  Created by Roman Abuzyarov on 27.02.2018.
//  Copyright (c) 2018 Tram, inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Lists
{
    // MARK: Use cases
    
    enum Watchlist
    {
        struct Request
        {
        }
        struct Response
        {
            var watchlist: [Movie]
        }
        struct ViewModel
        {
            var watchlist: [Movie]
        }
    }
    
    enum Watched{
        struct Request{}
        struct Response {
            var watched: [Movie]
        }
        struct ViewModel {
            var watched: [Movie]
        }
    }
}
