//
//  ListsPresenter.swift
//  Tram
//
//  Created by Roman Abuzyarov on 27.02.2018.
//  Copyright (c) 2018 Tram, inc.. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListsPresentationLogic
{
    func presentWatchlist(response: Lists.Watchlist.Response)
    func presentWatched(response: Lists.Watched.Response)
}

class ListsPresenter: ListsPresentationLogic
{
    func presentWatched(response: Lists.Watched.Response) {
        let viewModel = Lists.Watched.ViewModel(watched: response.watched)
        viewController?.displayWatched(viewModel: viewModel)
    }
    
    weak var viewController: ListsDisplayLogic?
    
    // MARK: Do something
    
    func presentWatchlist(response: Lists.Watchlist.Response)
    {
        let viewModel = Lists.Watchlist.ViewModel(watchlist: response.watchlist)
        viewController?.displayWatchlist(viewModel: viewModel)
    }
}
