//
//  MovieDetailsWorker.swift
//  Tram
//
//  Created by Roman Abuzyarov on 06.01.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Parse

class MovieDetailsWorker
{
    func list(movie: Movie, name: MovieDetails.List.Name, action: MovieDetails.List.Action, onSuccess: (MovieDetails.List.Name, MovieDetails.List.Status)->Void){
        let ud = UserDefaults.standard
        
        var tkey: String?
        switch name {
        case .Watchlist:
            tkey = "watchlist_movie"
        case .Watched:
            tkey = "watched_movie"
        }
        guard let key = tkey else{
            return
        }
        
        var list = ud.stringArray(forKey: key) ?? []
        var status = list.contains(String(movie.id))
        
        switch action {
        case .RequestStatus:
            break
        case .Add:
            if !status{
                list.append(String(movie.id))
            }
        case .Remove:
            if status{
                if let index = list.index(of: String(movie.id)){
                    list.remove(at: index)
                }
            }
        case .Change:
            if status {
                if let index = list.index(of: String(movie.id)){
                    list.remove(at: index)
                }
            }
            else {
                list.append(String(movie.id))
            }
        }
        
        status = list.contains(String(movie.id))
        
        ud.set(list, forKey: key)
        
        if status {
            onSuccess(name, .In)
        }
        else {
            onSuccess(name, .Out)
        }
    }
    
}
