//
//  MovieDetailsModels.swift
//  Tram
//
//  Created by Roman Abuzyarov on 06.01.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetails
{
    enum FillData
    {
        struct Request
        {
        }
        struct Response
        {
            var movie : Movie?
        }
        struct ViewModel
        {
            var title: String?
            var year: String?
            var length: String?
            var genres: String?
            var heartRating: String?
            var starRating: String?
            var imageUrl: String?
            
            var plot: String?
            
            var details: [(key: String?, value: String?)]
        }
    }
    
    enum LoadPeople{
        enum JobType{
            case Crew
            case Cast
        }
        
        struct Request{
            var type : JobType
        }
        
        struct Response{
            var type: JobType
            var people: [Job]
        }
        
        struct ViewModel{
            var people:[Job]
        }
    }
    
    enum Watchlist{
        enum Status{
            case In
            case Out
        }
        enum Action{
            case Add
            case Remove
            case RequestStatus
            case Change
        }
        
        struct Request {
            var action : Action
        }
        struct Response {
            var status : Status
        }
        struct ViewModel{
            var status : Status
        }
    }
}
