//
//  MovieDetailsInteractor.swift
//  tram-clean
//
//  Created by Roman Abuzyarov on 06.01.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsBusinessLogic
{
    func fillData(request: MovieDetails.FillData.Request)
}

protocol MovieDetailsDataStore
{
    var movie: Movie? { get set }
}

class MovieDetailsInteractor: MovieDetailsBusinessLogic, MovieDetailsDataStore
{
    var movie: Movie?
    
    var presenter: MovieDetailsPresentationLogic?
    var worker: MovieDetailsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func fillData(request: MovieDetails.FillData.Request)
    {
        let response = MovieDetails.FillData.Response(movie: movie)
        presenter?.fillData(response: response)
    }
}
