//
//  MovieDetailsWorker.swift
//  Tram
//
//  Created by Roman Abuzyarov on 06.01.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Parse

class MovieDetailsWorker
{
    func watchlist(movie: Movie, action: MovieDetails.Watchlist.Action, onSuccess: (MovieDetails.Watchlist.Status)->Void){
        let ud = UserDefaults.standard
        let key = "watchlist_movie"
        var list = ud.stringArray(forKey: key) ?? []
        var status = list.contains(String(movie.id))
        
        switch action {
        case .RequestStatus:
            break
        case .Add:
            if !status{
                list.append(String(movie.id))
            }
        case .Remove:
            if status{
                if let index = list.index(of: String(movie.id)){
                    list.remove(at: index)
                }
            }
        case .Change:
            if status {
                if let index = list.index(of: String(movie.id)){
                    list.remove(at: index)
                }
            }
            else {
                list.append(String(movie.id))
            }
        }
        
        status = list.contains(String(movie.id))
        
        ud.set(list, forKey: key)
        
        if status {
            onSuccess(.In)
        }
        else {
            onSuccess(.Out)
        }
    }
    
    func loadCast(of movie: Movie, onSuccess: @escaping ([Cast])->Void){
        let worker = ParseWorker()
        worker.loadCast(of: movie, onSuccess: onSuccess)
    }
    
    func loadCrew(of movie: Movie, onSuccess: @escaping ([Crew])->Void){
        let worker = ParseWorker()
        worker.loadCrew(of: movie, onSuccess: onSuccess)
    }
}
