//
//  MovieDetailsModels.swift
//  Tram
//
//  Created by Roman Abuzyarov on 06.01.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetails
{
    enum FillData
    {
        struct Request
        {
        }
        struct Response
        {
            var movie : Movie?
        }
        struct ViewModel
        {
            var movie : Movie?
        }
    }
    
    enum List{
        struct Request {
            var list: ListName
            var action : Action
        }
        struct Response {
            var list: ListName
            var status : Status
            var action : Action
        }
        struct ViewModel{
            var list: ListName
            var status : Status
            var action : Action
        }
    }
}
