//
//  MovieDetailsInteractor.swift
//  Tram
//
//  Created by Roman Abuzyarov on 06.01.2018.
//  Copyright (c) 2018 Roman Abuzyarov. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailsBusinessLogic
{
    func fillData(request: MovieDetails.FillData.Request)
    func list(request: MovieDetails.List.Request)
}

protocol MovieDetailsDataStore
{
    var movie: Movie? { get set }
}

class MovieDetailsInteractor: MovieDetailsBusinessLogic, MovieDetailsDataStore
{
    var movie: Movie?
    
    var presenter: MovieDetailsPresentationLogic?
    var worker: MovieDetailsWorker?
    
    init(){
        worker = MovieDetailsWorker()
    }
    
    func fillData(request: MovieDetails.FillData.Request)
    {
        let response = MovieDetails.FillData.Response(movie: movie)
        presenter?.fillData(response: response)
    }
    
    func list(request: MovieDetails.List.Request){
        if let movie = movie{
            worker?.list(movie: movie, name: request.list, action: request.action, onSuccess: { (list, status, action) in
                self.presenter?.presentList(response: MovieDetails.List.Response(list: list, status: status, action: action))
            })
        }
    }
}
